version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: wa-akg-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wa_akg
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wa-akg-app
    restart: always
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db:3306/wa_akg
      - AUTH_SECRET=w6PO4cY5PgJ0VSipJHLK7z0PLx/tWCrYROqGDPIjsm8=
      - BASE_URL=http://localhost:3000
      - NEXTAUTH_URL=http://localhost:3000
      - NODE_ENV=production
      - PORT=3003
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
      - BAILEYS_LOG_LEVEL=error
      - NEXT_PUBLIC_SWAGGER_USERNAME=admin
      - NEXT_PUBLIC_SWAGGER_PASSWORD=admin123
      - NEXT_PUBLIC_SWAGGER_ENABLED=true
      - TZ=Asia/Jakarta
      - LOCALE=id-ID
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=admin123
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - app_data:/app/data
      - uploads_data:/app/public/uploads

volumes:
  mysql_data:
  app_data:
  uploads_data:
